### ISSUE TITLE
t/02-approver.t started to fail

### ISSUE THREAD

**Issue by eserte** [rsimoes/WWW-eNom#9]
Since 2015-01-14 the test suite is failing. See http://matrix.cpantesters.org/?dist=WWW-eNom%20v1.3.0;reports=1#sl=7,1 for an overview (and links to sample reports).

**Comment by richard-ctcl** [comment]
It looks like a contact email in the whois data was changed. I'll test when I get a chance this weekend.

**Comment by rsimoes** [comment]
It looks like a contact email in the whois data was changed. I'll test when I get a chance this weekend.

**Comment by rsimoes** [comment]
Fixed in 1323d30c0d3d0e66900bd9c030f4871a60ad1a7c
